### ISSUE TITLE
Raw data question for Maze reaching

### ISSUE THREAD

**Issue by joel99** [catalystneuro/shenoy-lab-to-nwb#8]
Hi, I've recently been looking at the DANDI release ( https://dandiarchive.org/dandiset/000070/draft ) for the reaching dataset and have two questions.
1) I notice a drastic base firing rate difference in the datasets here and in another maze dataset released for the neural latents benchmark. I plot the rasters from the two datasets here, for example:
![image](https://user-images.githubusercontent.com/14226466/209002539-3a7aa907-de26-4889-abef-74b111e7f706.png)
![image](https://user-images.githubusercontent.com/14226466/209002618-1a95f56e-b2d2-47b5-b1c4-24407d09222a.png)

This DANDI release has average firing 50Hz, while the benchmark has average firing ~5Hz.  Even accounting for sorting, it seems unlikely that the MUA in this release should be 10x. Is there some filter I am missing? This DANDI raster seems to have some line noise, perhaps?

2) Are there raw (non-NWB) datasets available for the maze datasets? I ask because I saw some funky non-ascending/overlapping spike times stored in some of the NWB files (the dataset producing the above image was fine in this regard) and was wondering whether the conversion process might have introduced a bug.

**Comment by joel99** [comment]
cc @Saksham20 , who made these files

**Comment by bendichter** [comment]
Hi @joel99 thanks for bringing this to our attention and sorry for the delayed response. I'm just getting back from holiday break. I'll look into these files and see if we see similar FR in the source files.

**Comment by joel99** [comment]
Thanks! Gentle query if you've gotten the chance to look at this yet?

**Comment by bendichter** [comment]
Hi @joel99, I'm looking into this now. Thanks for your patience.

**Comment by bendichter** [comment]
First of all, thank you for raising this issue. It's great to see a DANDI user doing a comparative analysis between these types of datasets from different labs.

I plotted the spike times from the original data and got a similar raster:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/844306/213184101-0e226609-b2ac-4c5a-b5ee-328bfaf416cc.png">

I get a mean of ~38 Hz, which is roughly consistent with your analysis. We aren't looking at the same trial, so you wouldn't expect the numbers to match perfectly.

One idea why this might be so different from the Sabes dataset might be that the Shenoy data is unsorted. They don't got through the processing step of separating out spikes and just report threshold crossings per channel. The Sabes dataset might instead examine each spike waveform and cluster them (which would divide the avg fr by the # of groups per channel) and remove waveforms that cannot be grouped (which would further reduce the avg fr).

If you want to do a good comparison between different labs, I think you'll need to do the same preprocessing, e.g. filtering, spike sorting, etc. Those types of decisions can have a big impact on the statistics of the resulting data, and I would expect these types of issues to continue to arise.

> Are there raw (non-NWB) datasets available for the maze datasets? I ask because I saw some funky non-ascending/overlapping spike times stored in some of the NWB files (the dataset producing the above image was fine in this regard) and was wondering whether the conversion process might have introduced a bug.

You can see from the conversion script that we take the spike times as written and copy them to NWB:

https://github.com/catalystneuro/shenoy-lab-to-nwb/blob/0603061fdbcff8e5dad71ce38981cc4c2e352cc1/maze_task/matextractor.py#L29-L40

There's nothing fancy going on here, so any issues you have with the spike times in the NWB files I would expect you to also find in the source files.

**Comment by joel99** [comment]
Thanks for checking. OK, good to know! Do you have thoughts on the mismatch in the shape of `ir` and `jc` columns in the Reggie/Jenkins .mat files?

**Comment by joel99** [comment]
A reminder ping here?

**Comment by bendichter** [comment]
Sorry @joel99, I've been swamped. I believe they are using: csc_matrix notation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html#scipy-sparse-csc-matrix

See the last argspec:
> `csc_matrix((data, indices, indptr), [shape=(M, N)])`:
is the standard CSC representation where the row indices for column i are stored in indices[indptr[i]:indptr[i+1]] and their corresponding values are stored in data[indptr[i]:indptr[i+1]]. If the shape parameter is not supplied, the matrix dimensions are inferred from the index arrays.

I think what they are doing is `csc_matrix((data, ir, jc))`. So the length of `jc` would be the number of columns and the length of `ir` and of `data` should be the number of non-zero datapoints.

**Comment by joel99** [comment]
Brilliant, thank you! Sorry for the spam.
